### ISSUE TITLE
Syntax Error : command = f"install_name_tool {dylib_path} -id {new_name}"

### ISSUE THREAD

**Issue by mufaawan** [sighthoundinc/SighthoundVideo#10]
@w3sip  I executed the said file using `bash ./app` but I am seeing the error. I am attaching the whole log. Can you please tell me what I am doing wrong?

I am using `Python 2.7` with `pip 20.3.4`. I have already install `wxPython 4.0.7` using pip. 

```
C:\Users\mufaa\Documents\Work\SighthoundVideo>bash ./app
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\conan.exe\__main__.py", line 4, in <module>
  File "c:\python27\lib\site-packages\conans\conan.py", line 7, in <module>
    from conans.client.command import main
  File "c:\python27\lib\site-packages\conans\client\command.py", line 16, in <module>
    from conans.client.conan_api import Conan, default_manifest_folder, _make_abs_path, ProfileData
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 13, in <module>
    from conans.client.cmd.create import create
  File "c:\python27\lib\site-packages\conans\client\cmd\create.py", line 3, in <module>
    from conans.client.cmd.test import install_build_and_test
  File "c:\python27\lib\site-packages\conans\client\cmd\test.py", line 6, in <module>
    from conans.client.manager import deps_install
  File "c:\python27\lib\site-packages\conans\client\manager.py", line 7, in <module>
    from conans.client.installer import BinaryInstaller, call_system_requirements
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 11, in <module>
    from conans.client.generators import TXTGenerator, write_toolchain
  File "c:\python27\lib\site-packages\conans\client\generators\__init__.py", line 23, in <module>
    from .markdown import MarkdownGenerator
  File "c:\python27\lib\site-packages\conans\client\generators\markdown.py", line 8, in <module>
    from conan.tools.cmake.cmakedeps.cmakedeps import CMakeDeps
  File "c:\python27\lib\site-packages\conan\tools\cmake\__init__.py", line 1, in <module>
    from conan.tools.cmake.toolchain.toolchain import CMakeToolchain
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\toolchain.py", line 12, in <module>
    from conan.tools.cmake.toolchain.blocks import ToolchainBlocks, UserToolchain, GenericSystemBlock, \
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\blocks.py", line 9, in <module>
    from conan.tools.apple.apple import is_apple_os, to_apple_arch
  File "c:\python27\lib\site-packages\conan\tools\apple\__init__.py", line 8, in <module>
    from conan.tools.apple.apple import fix_apple_shared_install_name
  File "c:\python27\lib\site-packages\conan\tools\apple\apple.py", line 170
    command = f"install_name_tool {dylib_path} -id {new_name}"
                                                             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\conan.exe\__main__.py", line 4, in <module>
  File "c:\python27\lib\site-packages\conans\conan.py", line 7, in <module>
    from conans.client.command import main
  File "c:\python27\lib\site-packages\conans\client\command.py", line 16, in <module>
    from conans.client.conan_api import Conan, default_manifest_folder, _make_abs_path, ProfileData
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 13, in <module>
    from conans.client.cmd.create import create
  File "c:\python27\lib\site-packages\conans\client\cmd\create.py", line 3, in <module>
    from conans.client.cmd.test import install_build_and_test
  File "c:\python27\lib\site-packages\conans\client\cmd\test.py", line 6, in <module>
    from conans.client.manager import deps_install
  File "c:\python27\lib\site-packages\conans\client\manager.py", line 7, in <module>
    from conans.client.installer import BinaryInstaller, call_system_requirements
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 11, in <module>
    from conans.client.generators import TXTGenerator, write_toolchain
  File "c:\python27\lib\site-packages\conans\client\generators\__init__.py", line 23, in <module>
    from .markdown import MarkdownGenerator
  File "c:\python27\lib\site-packages\conans\client\generators\markdown.py", line 8, in <module>
    from conan.tools.cmake.cmakedeps.cmakedeps import CMakeDeps
  File "c:\python27\lib\site-packages\conan\tools\cmake\__init__.py", line 1, in <module>
    from conan.tools.cmake.toolchain.toolchain import CMakeToolchain
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\toolchain.py", line 12, in <module>
    from conan.tools.cmake.toolchain.blocks import ToolchainBlocks, UserToolchain, GenericSystemBlock, \
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\blocks.py", line 9, in <module>
    from conan.tools.apple.apple import is_apple_os, to_apple_arch
  File "c:\python27\lib\site-packages\conan\tools\apple\__init__.py", line 8, in <module>
    from conan.tools.apple.apple import fix_apple_shared_install_name
  File "c:\python27\lib\site-packages\conan\tools\apple\apple.py", line 170
    command = f"install_name_tool {dylib_path} -id {new_name}"
                                                             ^
SyntaxError: invalid syntax
pyfolder=
Python is already activated!
/c/Python27/python
Running bash ./run
=================================================================== Running setupEnvironment in /c/Users/mufaa/Documents/Work/SighthoundVideo
Params passed , params count 0
/c/Python27/python
PYTHONPATH=
SVINSTALLDIR=/c/Users/mufaa/Documents/Work/SighthoundVideo/build/stagingRoot
SV3RDPARTYDIR=/c/Users/mufaa/Documents/Work/SighthoundVideo/build/stagingRoot
['', 'C:\\Windows\\SYSTEM32\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\\lib', 'C:\\Python27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk', 'C:\\Python27', 'C:\\Python27\\lib\\site-packages']
PYTHONPATH=;C:\Users\mufaa\Documents\Work\SighthoundVideo;C:\Users\mufaa\Documents\Work\SighthoundVideo/xnat;C:\Users\mufaa\Documents\Work\SighthoundVideo/launch;C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\lib\python2.7\site-packages
PATH=/mingw64/bin:/usr/bin:/c/Users/mufaa/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/VC/VCPackages:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/bin/Roslyn:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Team Tools/Performance Tools/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Team Tools/Performance Tools:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/x64:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools:/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/x64:/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/Tools:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/cmd:/c/Users/mufaa/AppData/Local/Microsoft/WindowsApps:/c/Users/mufaa/AppData/Local/Programs/Microsoft VS Code/bin:/c/Program Files/CMake/bin:/bin:/usr/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/cmd:/c/Program Files/LLVM/bin:/c/ninja-win:/c/Python27:/c/Python27/Scripts:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja:C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin:C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin
Python=/c/Python27/python
=================================================================== Done running setupEnvironment
Environment is already set up!
Traceback (most recent call last):
  File "frontEnd/FrontEnd.py", line 42, in <module>
    from FrontEndApp import main
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\FrontEndApp.py", line 63, in <module>
    from BackEndClient import BackEndClient
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\BackEndClient.py", line 68, in <module>
    from frontEnd.FrontEndUtils import getUserLocalDataDir
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\FrontEndUtils.py", line 48, in <module>
    from launch.Launch import Launch
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\launch\Launch.py", line 127, in <module>
    _launchlib = LoadLibrary(None, _libName)
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\vitaToolbox\ctypesUtils\LoadLibrary.py", line 161, in LoadLibrary
    raise Exception("Could not load library " + libName + "; tried " + tried)
Exception: Could not load library launch; tried ;launch in None;liblaunch in None;launch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin;liblaunch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin;launch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin;liblaunch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin

C:\Users\mufaa\Documents\Work\SighthoundVideo>
```

**Comment by mufaawan** [comment]
most probably it's `conan` issue. Can you please tell me your `conan` version?

I changed the conan version to `1.60.0` and now getting this error. 
```
PS C:\Users\mufaa\Documents\Work\SighthoundVideo> bash .\app
ERROR: Conanfile not found: C:\Users\mufaa\Documents\Work\SighthoundVideo\conanfile.txt
ERROR: Conanfile not found: C:\Users\mufaa\Documents\Work\SighthoundVideo\conanfile.py
pyfolder=
Python is already activated!
/c/Python27/python
Running bash ./run
=================================================================== Running setupEnvironment in /c/Users/mufaa/Documents/Work/SighthoundVideo
Params passed , params count 0
/c/Python27/python
PYTHONPATH=
SVINSTALLDIR=/c/Users/mufaa/Documents/Work/SighthoundVideo/build/stagingRoot
SV3RDPARTYDIR=/c/Users/mufaa/Documents/Work/SighthoundVideo/build/stagingRoot
['', 'C:\\Windows\\SYSTEM32\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\\lib', 'C:\\Python27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27', 'C:\\Python27\\lib\\site-packages']
PYTHONPATH=;C:\Users\mufaa\Documents\Work\SighthoundVideo;C:\Users\mufaa\Documents\Work\SighthoundVideo/xnat;C:\Users\mufaa\Documents\Work\Sightho
undVideo/launch;C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\lib\python2.7\site-packages
PATH=/mingw64/bin:/usr/bin:/c/Users/mufaa/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/
cmd:/c/Users/mufaa/AppData/Local/Microsoft/WindowsApps:/c/Users/mufaa/AppData/Local/Programs/Microsoft VS Code/bin:/c/Program Files/CMake/bin:/bin
:/usr/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/cmd:/c/Program Files/LLVM/bin:/c/nin
ja-win:/c/Python27:/c/Python27/Scripts:C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin:C:\Users\mufaa\Documents\Work\Sighthoun
dVideo\build\stagingRoot\bin
Python=/c/Python27/python
=================================================================== Done running setupEnvironment
Environment is already set up!
Traceback (most recent call last):
  File "frontEnd/FrontEnd.py", line 42, in <module>
    from FrontEndApp import main
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\FrontEndApp.py", line 63, in <module>
    from BackEndClient import BackEndClient
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\BackEndClient.py", line 68, in <module>
    from frontEnd.FrontEndUtils import getUserLocalDataDir
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\FrontEndUtils.py", line 48, in <module>
    from launch.Launch import Launch
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\launch\Launch.py", line 127, in <module>
    _launchlib = LoadLibrary(None, _libName)
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\vitaToolbox\ctypesUtils\LoadLibrary.py", line 161, in LoadLibrary
    raise Exception("Could not load library " + libName + "; tried " + tried)
Exception: Could not load library launch; tried ;launch in None;liblaunch in None;launch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\st
agingRoot\bin;liblaunch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin;launch in C:\Users\mufaa\Documents\Work\SighthoundV
ideo\build\stagingRoot\bin;liblaunch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin
PS C:\Users\mufaa\Documents\Work\SighthoundVideo>
```
