### ISSUE TITLE
cl-lang.exe is not able to compile simple test program.

### ISSUE THREAD

**Issue by mufaawan** [sighthoundinc/SighthoundVideo#5]
hello,
I have been trying to build on windows 11 and I am using VIsual Studio 2017, LLVM10 and Cmake 3.17.1. I am getting the following error. 

```
./svpython/Tools/versioncheck/
./svpython/Tools/versioncheck/checkversions.py
./svpython/Tools/versioncheck/pyversioncheck.py
./svpython/Tools/versioncheck/README.txt
./svpython/Tools/versioncheck/_checkversion.py
./svpython/Tools/webchecker/
./svpython/Tools/webchecker/README.txt
./svpython/Tools/webchecker/tktools.py
./svpython/Tools/webchecker/wcgui.py
./svpython/Tools/webchecker/wcmac.py
./svpython/Tools/webchecker/webchecker.py
./svpython/Tools/webchecker/websucker.py
./svpython/Tools/webchecker/wsgui.py
SV3RDPARTYDIR=/tmp/svbuild/win/libs
Building launch from /c/Users/mufaa/Documents/Work/Sighthound/SighthoundVideo-main/launch into /tmp/svbuild/win/install
/tmp/svbuild/win/launch/.build ~/Documents/Work/Sighthound/SighthoundVideo-main
Building /c/Users/mufaa/Documents/Work/Sighthound/SighthoundVideo-main/launch for Windows
-- The C compiler identification is Clang 10.0.0 with MSVC-like command-line
-- The CXX compiler identification is Clang 10.0.0 with MSVC-like command-line
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files/LLVM/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/mufaa/AppData/Local/Temp/svbuild/win/launch/.build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/ninja-win/ninja.exe cmTC_a4498 && [1/2] Building C object CMakeFiles\cmTC_a4498.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_a4498.exe
    FAILED: cmTC_a4498.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_a4498.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo CMakeFiles\cmTC_a4498.dir\testCCompiler.c.obj  /out:cmTC_a4498.exe /implib:cmTC_a4498.lib /pdb:cmTC_a4498.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo CMakeFiles\cmTC_a4498.dir\testCCompiler.c.obj /out:cmTC_a4498.exe /implib:cmTC_a4498.lib /pdb:cmTC_a4498.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_a4498.dir/intermediate.manifest CMakeFiles\cmTC_a4498.dir/manifest.res" failed (exit code 1) with the following output:
    lld-link: error: <root>: undefined symbol: mainCRTStartup
    ninja: build stopped: subcommand failed.


CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/mufaa/AppData/Local/Temp/svbuild/win/launch/.build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/mufaa/AppData/Local/Temp/svbuild/win/launch/.build/CMakeFiles/CMakeError.log".
Failed to build /c/Users/mufaa/Documents/Work/Sighthound/SighthoundVideo-main/launch (cmake)

C:\Users\mufaa\Documents\Work\Sighthound\SighthoundVideo-main>
```

**Comment by w3sip** [comment]
Could you please provide the entire log, starting from the command you've ran, as well as the output of `bash -c "which make"` and `bash -c "make --version"` ?

**Comment by mufaawan** [comment]
Commands results. 
```
C:\Users\usman\Documents\Umar\Sighthound\SighthoundVideo>bash -c "which make"
/mingw64/bin/make
```
and 
```
C:\Users\usman\Documents\Umar\Sighthound\SighthoundVideo>bash -c "make --version"
GNU Make 4.4.1
Built for x86_64-pc-msys
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

The log is too long to match the allowed character lenght of github comment. I have attached a text file. 
[Command-prompt-log.txt](https://github.com/sighthoundinc/SighthoundVideo/files/12283318/Command-prompt-log.txt)


Here's list of all environment variables. 
![image](https://github.com/sighthoundinc/SighthoundVideo/assets/17979287/cb970e56-228a-4771-b19b-18830d56ce81)

**Comment by mufaawan** [comment]
I am using the make from `msys2` as per instructions in this comment. 
https://github.com/sighthoundinc/SighthoundVideo/issues/3#issuecomment-1507486157

**Comment by w3sip** [comment]
Okay, I've attempted to reproduce -- but no luck, seems to build. This is the script I've used:

```
set PATH=u:\cmake-3.17.1\bin;u:\git\bin;u:\git\usr\bin;%PATH%;u:\llvm10\bin;u:\make
echo "=============================="
bash -c "which make"
echo "=============================="
bash -c "make --version"
echo "=============================="
ninja --version
echo "=============================="
set
bash buildSV.sh
```

Your make version seems to be correct (and matching mine)

**Comment by w3sip** [comment]
This is the output I'm seeing:

```
u:\code\SighthoundVideo>echo "=============================="
"=============================="

u:\code\SighthoundVideo>bash -c "make --version"
GNU Make 4.4.1
Built for x86_64-pc-msys
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

u:\code\SighthoundVideo>echo "=============================="
"=============================="

u:\code\SighthoundVideo>ninja --version
1.11.0
```

Just to confirm -- you're running from the MSVC command prompt (i.e. this):

<img width="773" alt="Screen Shot 2023-08-07 at 1 22 29 PM" src="https://github.com/sighthoundinc/SighthoundVideo/assets/4392548/58b0978b-021e-4483-abb8-eb607f75745a">

**Comment by w3sip** [comment]
One thing that I see -- you have `.\Git\mingw64\bin` on PATH. That has a chance of introducing mingw toolchain utilities into the mix (with the outcome being a mixup not unlike the one you're seeing).

**Comment by mufaawan** [comment]
> This is the output I'm seeing:
> 
> ```
> u:\code\SighthoundVideo>echo "=============================="
> "=============================="
> 
> u:\code\SighthoundVideo>bash -c "make --version"
> GNU Make 4.4.1
> Built for x86_64-pc-msys
> Copyright (C) 1988-2023 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> u:\code\SighthoundVideo>echo "=============================="
> "=============================="
> 
> u:\code\SighthoundVideo>ninja --version
> 1.11.0
> ```
> 
> Just to confirm -- you're running from the MSVC command prompt (i.e. this):
> 
> <img alt="Screen Shot 2023-08-07 at 1 22 29 PM" width="773" src="https://user-images.githubusercontent.com/4392548/258881342-58b0978b-021e-4483-abb8-eb607f75745a.png">

I am using the mentioned cmd prompt. 

My ninja version is `1.11.1`

Also my `bash -c "make --version"` shows exact output as yours.

**Comment by mufaawan** [comment]
> One thing that I see -- you have `.\Git\mingw64\bin` on PATH. That has a chance of introducing mingw toolchain utilities into the mix (with the outcome being a mixup not unlike the one you're seeing).

What solution do you recommend here? I have collected make.exe and placed in my ./git/mingw64/bin as per instrctions here. 
<img width="696" alt="image" src="https://github.com/sighthoundinc/SighthoundVideo/assets/17979287/9ae3759d-fa00-4fc9-8d0a-5e327460c3c4">

**Comment by w3sip** [comment]
This mirrors my setup here -- except I don't have anything `mingw64`-related on PATH. Git bash seems to be able to locate `make` without added entries, and having mingw compiler toolchain on PATH seems to interfere with CMake/MSVC ability to build.

**Comment by mufaawan** [comment]
Seems like the `C:/Program Files(x86)/Inno Setup 5` has been hard coded somewhere?

**Comment by w3sip** [comment]
You're correct

> Seems like the `C:/Program Files(x86) Inno Setup 5` has been hard coded somewhere?

You're correct: here it is - https://github.com/sighthoundinc/SighthoundVideo/blob/main/frontEnd/WinInstaller.py#L500

**Comment by w3sip** [comment]
> I will create PR. Are you accepting PRs by any chance?

While it will not be merged immediately, since published version of SV is a derivative of a closed source SV, with some things like cloud connectivity (bug reporting, licensing, etc) and proprietary models being stripped out, we will definitely accept code contributions and integrate them for future updates after vetting.

**Comment by mufaawan** [comment]
Thank you so much. I will make a proper guide with right link to resources and create a PR. I am closing the issue. 

PS: Sorry for a deleted comment mentioning the PR of updated readme.md.

**Comment by mufaawan** [comment]
Issue resolved.

**Comment by mufaawan** [comment]
@w3sip log says the installer file has been generated. But I couldn't find the file on path. 
`C:\Users\usman\AppData\Local\Temp\.build-obs\installer-out\frontEnd-Win\Sighthound Video Setup.exe`

Does it has to do something with signing with Inno?

![image](https://github.com/sighthoundinc/SighthoundVideo/assets/17979287/d1c0b8bc-2413-41bc-8222-f5150c2f5d83)

**Comment by w3sip** [comment]
No, signing is optional. I'll need to see why, but the installer ends up in ` ./build/installer-out/frontEnd-Win/`:

```
u:\code\SighthoundVideo>dir .\build\installer-out\frontEnd-Win
 Volume in drive U is WORK_M2
 Volume Serial Number is 889D-1D0A

 Directory of u:\code\SighthoundVideo\build\installer-out\frontEnd-Win

08/07/2023  01:03 PM    <DIR>          .
08/07/2023  01:03 PM    <DIR>          ..
08/07/2023  01:04 PM       451,375,061 Sighthound Video Setup.exe
               1 File(s)    451,375,061 bytes
               2 Dir(s)  30,003,245,056 bytes free
```

**Comment by mufaawan** [comment]
Ok, I can see it inside the root directory of the project. I thought path for installer is inside `AppData/Local/Temp/.build-obs` like mentioned in printed messages in the screenshot.

**Comment by w3sip** [comment]
Yes, definitely inconsistent -- will investigate.

**Comment by w3sip** [comment]
@mufaawan - looks like it's being moved after creation. Probably to make it more accessible than a temp build folder, but yes, a bit confusing:
https://github.com/sighthoundinc/SighthoundVideo/blob/main/frontEnd/FrontEnd.mk#L256

**Comment by mufaawan** [comment]
@w3sip how would I execute the project to test during development? I mean what's the `start command`? I want to make some changes and test the project during change implementation.

**Comment by w3sip** [comment]
@mufaawan - Try working with this: https://github.com/sighthoundinc/SighthoundVideo/blob/main/app

**Comment by mufaawan** [comment]
@w3sip  I executed the said file using `bash ./app` but I am seeing the error. I am attaching the whole log. Can you please tell me what I am doing wrong?

I am using `Python 2.7` with `pip 20.3.4`. I have already install `wxPython 4.0.7` using pip. 


```
C:\Users\mufaa\Documents\Work\SighthoundVideo>bash ./app
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\conan.exe\__main__.py", line 4, in <module>
  File "c:\python27\lib\site-packages\conans\conan.py", line 7, in <module>
    from conans.client.command import main
  File "c:\python27\lib\site-packages\conans\client\command.py", line 16, in <module>
    from conans.client.conan_api import Conan, default_manifest_folder, _make_abs_path, ProfileData
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 13, in <module>
    from conans.client.cmd.create import create
  File "c:\python27\lib\site-packages\conans\client\cmd\create.py", line 3, in <module>
    from conans.client.cmd.test import install_build_and_test
  File "c:\python27\lib\site-packages\conans\client\cmd\test.py", line 6, in <module>
    from conans.client.manager import deps_install
  File "c:\python27\lib\site-packages\conans\client\manager.py", line 7, in <module>
    from conans.client.installer import BinaryInstaller, call_system_requirements
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 11, in <module>
    from conans.client.generators import TXTGenerator, write_toolchain
  File "c:\python27\lib\site-packages\conans\client\generators\__init__.py", line 23, in <module>
    from .markdown import MarkdownGenerator
  File "c:\python27\lib\site-packages\conans\client\generators\markdown.py", line 8, in <module>
    from conan.tools.cmake.cmakedeps.cmakedeps import CMakeDeps
  File "c:\python27\lib\site-packages\conan\tools\cmake\__init__.py", line 1, in <module>
    from conan.tools.cmake.toolchain.toolchain import CMakeToolchain
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\toolchain.py", line 12, in <module>
    from conan.tools.cmake.toolchain.blocks import ToolchainBlocks, UserToolchain, GenericSystemBlock, \
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\blocks.py", line 9, in <module>
    from conan.tools.apple.apple import is_apple_os, to_apple_arch
  File "c:\python27\lib\site-packages\conan\tools\apple\__init__.py", line 8, in <module>
    from conan.tools.apple.apple import fix_apple_shared_install_name
  File "c:\python27\lib\site-packages\conan\tools\apple\apple.py", line 170
    command = f"install_name_tool {dylib_path} -id {new_name}"
                                                             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\conan.exe\__main__.py", line 4, in <module>
  File "c:\python27\lib\site-packages\conans\conan.py", line 7, in <module>
    from conans.client.command import main
  File "c:\python27\lib\site-packages\conans\client\command.py", line 16, in <module>
    from conans.client.conan_api import Conan, default_manifest_folder, _make_abs_path, ProfileData
  File "c:\python27\lib\site-packages\conans\client\conan_api.py", line 13, in <module>
    from conans.client.cmd.create import create
  File "c:\python27\lib\site-packages\conans\client\cmd\create.py", line 3, in <module>
    from conans.client.cmd.test import install_build_and_test
  File "c:\python27\lib\site-packages\conans\client\cmd\test.py", line 6, in <module>
    from conans.client.manager import deps_install
  File "c:\python27\lib\site-packages\conans\client\manager.py", line 7, in <module>
    from conans.client.installer import BinaryInstaller, call_system_requirements
  File "c:\python27\lib\site-packages\conans\client\installer.py", line 11, in <module>
    from conans.client.generators import TXTGenerator, write_toolchain
  File "c:\python27\lib\site-packages\conans\client\generators\__init__.py", line 23, in <module>
    from .markdown import MarkdownGenerator
  File "c:\python27\lib\site-packages\conans\client\generators\markdown.py", line 8, in <module>
    from conan.tools.cmake.cmakedeps.cmakedeps import CMakeDeps
  File "c:\python27\lib\site-packages\conan\tools\cmake\__init__.py", line 1, in <module>
    from conan.tools.cmake.toolchain.toolchain import CMakeToolchain
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\toolchain.py", line 12, in <module>
    from conan.tools.cmake.toolchain.blocks import ToolchainBlocks, UserToolchain, GenericSystemBlock, \
  File "c:\python27\lib\site-packages\conan\tools\cmake\toolchain\blocks.py", line 9, in <module>
    from conan.tools.apple.apple import is_apple_os, to_apple_arch
  File "c:\python27\lib\site-packages\conan\tools\apple\__init__.py", line 8, in <module>
    from conan.tools.apple.apple import fix_apple_shared_install_name
  File "c:\python27\lib\site-packages\conan\tools\apple\apple.py", line 170
    command = f"install_name_tool {dylib_path} -id {new_name}"
                                                             ^
SyntaxError: invalid syntax
pyfolder=
Python is already activated!
/c/Python27/python
Running bash ./run
=================================================================== Running setupEnvironment in /c/Users/mufaa/Documents/Work/SighthoundVideo
Params passed , params count 0
/c/Python27/python
PYTHONPATH=
SVINSTALLDIR=/c/Users/mufaa/Documents/Work/SighthoundVideo/build/stagingRoot
SV3RDPARTYDIR=/c/Users/mufaa/Documents/Work/SighthoundVideo/build/stagingRoot
['', 'C:\\Windows\\SYSTEM32\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\\lib', 'C:\\Python27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk', 'C:\\Python27', 'C:\\Python27\\lib\\site-packages']
PYTHONPATH=;C:\Users\mufaa\Documents\Work\SighthoundVideo;C:\Users\mufaa\Documents\Work\SighthoundVideo/xnat;C:\Users\mufaa\Documents\Work\SighthoundVideo/launch;C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\lib\python2.7\site-packages
PATH=/mingw64/bin:/usr/bin:/c/Users/mufaa/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/VC/VCPackages:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/bin/Roslyn:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Team Tools/Performance Tools/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Team Tools/Performance Tools:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/x64:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools:/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/x64:/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/Tools:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/cmd:/c/Users/mufaa/AppData/Local/Microsoft/WindowsApps:/c/Users/mufaa/AppData/Local/Programs/Microsoft VS Code/bin:/c/Program Files/CMake/bin:/bin:/usr/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/cmd:/c/Program Files/LLVM/bin:/c/ninja-win:/c/Python27:/c/Python27/Scripts:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja:C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin:C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin
Python=/c/Python27/python
=================================================================== Done running setupEnvironment
Environment is already set up!
Traceback (most recent call last):
  File "frontEnd/FrontEnd.py", line 42, in <module>
    from FrontEndApp import main
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\FrontEndApp.py", line 63, in <module>
    from BackEndClient import BackEndClient
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\BackEndClient.py", line 68, in <module>
    from frontEnd.FrontEndUtils import getUserLocalDataDir
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\frontEnd\FrontEndUtils.py", line 48, in <module>
    from launch.Launch import Launch
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\launch\Launch.py", line 127, in <module>
    _launchlib = LoadLibrary(None, _libName)
  File "C:\Users\mufaa\Documents\Work\SighthoundVideo\vitaToolbox\ctypesUtils\LoadLibrary.py", line 161, in LoadLibrary
    raise Exception("Could not load library " + libName + "; tried " + tried)
Exception: Could not load library launch; tried ;launch in None;liblaunch in None;launch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin;liblaunch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin;launch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin;liblaunch in C:\Users\mufaa\Documents\Work\SighthoundVideo\build\stagingRoot\bin

C:\Users\mufaa\Documents\Work\SighthoundVideo>
```

**Comment by mufaawan** [comment]
@w3sip  I am waiting for response. :)
